[build]
  command = "npm run build"
  publish = ".next"
  environment = { SECRETS_SCAN_OMIT_PATHS = "public/firebase-messaging-sw.js,scripts" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/.well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
